version: '3.5'

services:
  frontend:
    build:
      context: .
      dockerfile: DockerFile
    expose: 
        - "3000"
    volumes: 
      - ./client:/app/
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev"]
  mongodb:
    image: mongo:4.4.10
    expose: 
      - "27017"
    ports:
      - "27017:27017"
